apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x2w79a9h1-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x2w79a9h1-nodejs 
  name: x2w79a9h1-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: x2w79a9h1-nodejs 
